#!/usr/bin/env python3
"""Test the New User button functionality"""

import requests
import json

def test_new_user_functionality():
    """Test that new user button creates fresh conversations"""

    print("Testing New User Button Functionality")
    print("=" * 50)

    # Test 1: First conversation
    session1 = "user_123"
    message1 = "I have chest pain"

    print(f"Test 1: Session {session1} - Message: '{message1}'")
    response1 = requests.post('http://localhost:8000/api/chat',
                            json={'message': message1, 'session_id': session1})

    if response1.status_code == 200:
        result1 = response1.json()
        print(f"Response: {result1['response'][:60]}...")
        print("✅ First conversation working")
    else:
        print("❌ First conversation failed")

    # Test 2: Same session continues conversation
    message2 = "John Doe"
    print(f"\nTest 2: Same session {session1} - Message: '{message2}'")
    response2 = requests.post('http://localhost:8000/api/chat',
                            json={'message': message2, 'session_id': session1})

    if response2.status_code == 200:
        result2 = response2.json()
        print(f"Response: {result2['response'][:60]}...")
        print("✅ Conversation continuation working")
    else:
        print("❌ Conversation continuation failed")

    # Test 3: New session (simulating "New User" button click)
    session2 = "user_456"  # This would be generated by the New User button
    message3 = "I have a headache"

    print(f"\nTest 3: New session {session2} - Message: '{message3}'")
    print("(This simulates clicking the 'New User' button)")
    response3 = requests.post('http://localhost:8000/api/chat',
                            json={'message': message3, 'session_id': session2})

    if response3.status_code == 200:
        result3 = response3.json()
        print(f"Response: {result3['response'][:60]}...")
        print("✅ New conversation working")
    else:
        print("❌ New conversation failed")

    print("\n" + "=" * 50)
    print("✅ New User button functionality verified!")
    print("Each new session starts fresh conversations independently.")

if __name__ == "__main__":
    test_new_user_functionality()